typography_spectrum: 0.9050584915094078
color:
  brandColors:
    - '#3C493F'
    - '#7E8D85'
    - '#B3BFB8'
    - '#F0F7F4'
    - '#A2E3C4'
  brandStrength: 0.3125
  lightness: 0.625
  saturation: 0.25
  rhythmicContrast: 0.25
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.6990634324029088
analytics:
  google: null
  facebook: null
  twitter: null
name: The Posts
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: School time!
description: ...return to normalcy
purpose: []
